FROM alpine:3.10.2

RUN apk update --no-cache &&\
    apk upgrade --no-cache &&\
    addgroup -S manager &&\
    adduser -h /home/manager -S -u 1000 -G manager manager

WORKDIR /home/manager/
COPY --chown=manager:manager bin/manager .

USER 1000

ENTRYPOINT ["./manager"]
